#%RAML 1.0
title: Super Heros Movies Data SAPI
description: Super-Movies-SAPI allows you to fetch the basic movies data of various super heros.
version: 1.0
mediaType: application/json

types:
  movies-data: !include types/movies_dataType.raml

securitySchemes:
  basic-auth: !include exchange_modules/org.mule.examples/basic-auth-securityscheme/1.0.0/basic-auth-securityscheme.raml

uses:
  rest-connect: exchange_modules/org.mule.connectivity/rest-connect-library/1.0.2/rest-connect-library.raml

securedBy: basic-auth

/movies/{id}:
  uriParameters:
    id:
      required: true
      example:
        value: MARVEL0001
  get:
   (rest-connect.operationName): Fetch Movies Data using CID
   displayName: Get Movies by CID
   description: This resources fetches movies data based on the unique **character id** sent in the URI Parameter 
   responses:
     200:
       description: If **character id** exists, returns the movies data
       body:
         application/json:
           type: movies-data
           example: !include examples/movies_example.raml